
server:
  port: 8998

#spring.mvc.view.prefix=/pages/
#spring.mvc.view.suffix=.html

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: system
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB